# Generated by Django 6.1.1 on 2026-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='foto de perfil'),
        ),
    ]
