# Generated by Django 6.1.1 on 2026-09-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avatar_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='capa do perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='foto de perfil'),
        ),
    ]
