# Generated by Django 6.1.1 on 2026-09-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name='foto da postagem',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
